services:
  api:
    build:
      context: .
      dockerfile: TaskForge.API/Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=${TASKFORGE_DB};User=sa;Password=${SA_PASSWORD};TrustServerCertificate=True

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    env_file:
      - .env
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data: